# Generated by Django 5.1.15 on 2026-07-09 13:18

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(db_index=True, max_length=150)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('mobile', models.CharField(blank=True, db_index=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('current_location', models.CharField(blank=True, db_index=True, max_length=150)),
                ('total_experience_years', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('relevant_experience_years', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('current_company', models.CharField(blank=True, db_index=True, max_length=150)),
                ('current_designation', models.CharField(blank=True, max_length=150)),
                ('highest_qualification', models.CharField(blank=True, max_length=150)),
                ('skills_cache', models.TextField(blank=True, editable=False)),
                ('current_salary', models.DecimalField(blank=True, decimal_places=2, help_text='Current CTC.', max_digits=12, null=True)),
                ('expected_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notice_period_days', models.PositiveIntegerField(blank=True, null=True)),
                ('last_working_day', models.DateField(blank=True, null=True)),
                ('candidate_status', models.CharField(choices=[('RESUME_RECEIVED', 'Resume Received'), ('SHORTLISTED', 'Shortlisted'), ('INTERVIEW_SCHEDULED', 'Interview Scheduled'), ('INTERVIEW_IN_PROGRESS', 'Interview In Progress'), ('INTERVIEW_COMPLETED', 'Interview Completed'), ('OFFER_RELEASED', 'Offer Released'), ('JOINED', 'Joined'), ('REJECTED', 'Rejected'), ('ON_HOLD', 'On Hold')], db_index=True, default='RESUME_RECEIVED', max_length=25)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['full_name'], name='cand_name_idx'), models.Index(fields=['email'], name='cand_email_idx'), models.Index(fields=['mobile'], name='cand_mobile_idx'), models.Index(fields=['current_location'], name='cand_location_idx'), models.Index(fields=['candidate_status', 'created_at'], name='cand_status_created_idx'), django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='cand_search_gin_idx')],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_id', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('job_role', models.CharField(db_index=True, max_length=150)),
                ('department', models.CharField(db_index=True, max_length=120)),
                ('hiring_manager', models.CharField(blank=True, max_length=150)),
                ('experience_min_years', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('experience_max_years', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('location', models.CharField(db_index=True, max_length=150)),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract'), ('INTERNSHIP', 'Internship'), ('TEMPORARY', 'Temporary')], default='FULL_TIME', max_length=20)),
                ('number_of_openings', models.PositiveIntegerField(default=1)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_currency', models.CharField(default='INR', max_length=3)),
                ('job_status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('CLOSED', 'Closed'), ('ON_HOLD', 'On Hold')], db_index=True, default='OPEN', max_length=20)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['job_status', 'is_archived'], name='job_status_arch_idx'), models.Index(fields=['department', 'job_status'], name='job_dept_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='CandidateJobMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mapping_status', models.CharField(choices=[('APPLIED', 'Applied'), ('UNDER_REVIEW', 'Under Review'), ('SHORTLISTED', 'Shortlisted'), ('INTERVIEWING', 'Interviewing'), ('OFFERED', 'Offered'), ('HIRED', 'Hired'), ('REJECTED', 'Rejected'), ('ON_HOLD', 'On Hold')], db_index=True, default='APPLIED', max_length=15)),
                ('applied_date', models.DateField(default=django.utils.timezone.localdate)),
                ('recruiter_name', models.CharField(blank=True, db_index=True, max_length=150)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_mappings', to='core.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_mappings', to='core.job')),
            ],
            options={
                'ordering': ['-applied_date'],
            },
        ),
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('summary', models.TextField(blank=True)),
                ('responsibilities', models.TextField(blank=True)),
                ('required_skills', models.TextField(blank=True, help_text='Free-text / comma-separated required skills.')),
                ('qualifications', models.TextField(blank=True)),
                ('benefits', models.TextField(blank=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='description', to='core.job')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('RESUME_UPLOADED', 'Resume Uploaded'), ('CANDIDATE_TAGGED', 'Candidate Tagged'), ('INTERVIEW_SCHEDULED', 'Interview Scheduled'), ('OFFER_RELEASED', 'Offer Released'), ('CANDIDATE_JOINED', 'Candidate Joined')], db_index=True, max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('object_type', models.CharField(blank=True, max_length=50)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offered_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('offer_status', models.CharField(choices=[('DRAFT', 'Draft'), ('RELEASED', 'Released'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('REVOKED', 'Revoked')], db_index=True, default='DRAFT', max_length=10)),
                ('offer_date', models.DateField(blank=True, null=True)),
                ('expected_joining_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('mapping', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='core.candidatejobmapping')),
            ],
            options={
                'ordering': ['-offer_date'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('notification_prefs', models.JSONField(blank=True, default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecruitmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, choices=[('RESUME_RECEIVED', 'Resume Received'), ('SHORTLISTED', 'Shortlisted'), ('INTERVIEW_SCHEDULED', 'Interview Scheduled'), ('INTERVIEW_IN_PROGRESS', 'Interview In Progress'), ('INTERVIEW_COMPLETED', 'Interview Completed'), ('OFFER_RELEASED', 'Offer Released'), ('JOINED', 'Joined'), ('REJECTED', 'Rejected'), ('ON_HOLD', 'On Hold')], max_length=25)),
                ('new_status', models.CharField(choices=[('RESUME_RECEIVED', 'Resume Received'), ('SHORTLISTED', 'Shortlisted'), ('INTERVIEW_SCHEDULED', 'Interview Scheduled'), ('INTERVIEW_IN_PROGRESS', 'Interview In Progress'), ('INTERVIEW_COMPLETED', 'Interview Completed'), ('OFFER_RELEASED', 'Offer Released'), ('JOINED', 'Joined'), ('REJECTED', 'Rejected'), ('ON_HOLD', 'On Hold')], max_length=25)),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('notes', models.TextField(blank=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='core.candidate')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to=settings.AUTH_USER_MODEL)),
                ('mapping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_history', to='core.candidatejobmapping')),
            ],
            options={
                'verbose_name_plural': 'Recruitment statuses',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('date_filter', models.CharField(choices=[('TODAY', 'Today'), ('YESTERDAY', 'Yesterday'), ('THIS_WEEK', 'This Week'), ('LAST_WEEK', 'Last Week'), ('THIS_MONTH', 'This Month'), ('LAST_MONTH', 'Last Month'), ('THIS_YEAR', 'This Year'), ('CUSTOM', 'Custom Date Range')], default='THIS_MONTH', max_length=12)),
                ('custom_start', models.DateField(blank=True, null=True)),
                ('custom_end', models.DateField(blank=True, null=True)),
                ('columns', models.JSONField(blank=True, default=list)),
                ('export_format', models.CharField(choices=[('EXCEL', 'Excel'), ('CSV', 'CSV'), ('PDF', 'PDF')], default='EXCEL', max_length=6)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='resumes/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_type', models.CharField(blank=True, choices=[('PDF', 'PDF'), ('DOC', 'DOC'), ('DOCX', 'DOCX')], max_length=5)),
                ('raw_text', models.TextField(blank=True)),
                ('parse_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('PARSED', 'Parsed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=12)),
                ('parse_error', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('parsed_at', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='core.candidate')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=6)),
                ('model_name', models.CharField(db_index=True, max_length=100)),
                ('object_id', models.CharField(db_index=True, max_length=64)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['model_name', 'object_id'], name='audit_model_obj_idx'), models.Index(fields=['timestamp'], name='audit_time_idx')],
            },
        ),
        migrations.CreateModel(
            name='CandidateExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=150)),
                ('designation', models.CharField(blank=True, max_length=150)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='core.candidate')),
            ],
            options={
                'ordering': ['-is_current', '-end_date', '-start_date'],
                'indexes': [models.Index(fields=['candidate', 'is_current'], name='exp_cand_current_idx')],
            },
        ),
        migrations.CreateModel(
            name='CandidateSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('skill_type', models.CharField(choices=[('SKILL', 'Skill'), ('TECHNOLOGY', 'Technology'), ('CERTIFICATION', 'Certification')], default='SKILL', max_length=15)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='core.candidate')),
            ],
            options={
                'indexes': [models.Index(fields=['name', 'skill_type'], name='skill_name_type_idx')],
                'constraints': [models.UniqueConstraint(fields=('candidate', 'name', 'skill_type'), name='uniq_candidate_skill')],
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interview_date', models.DateField(blank=True, null=True)),
                ('interview_time', models.TimeField(blank=True, null=True)),
                ('interview_round', models.CharField(blank=True, help_text="e.g. 'Technical Round 1', 'HR Round'.", max_length=100)),
                ('interviewer_name', models.CharField(blank=True, max_length=150)),
                ('feedback', models.TextField(blank=True)),
                ('result', models.CharField(choices=[('PENDING', 'Pending'), ('PASSED', 'Passed'), ('FAILED', 'Failed'), ('ON_HOLD', 'On Hold')], default='PENDING', max_length=10)),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='core.candidatejobmapping')),
            ],
            options={
                'ordering': ['interview_date', 'interview_time'],
                'indexes': [models.Index(fields=['interview_date'], name='interview_date_idx'), models.Index(fields=['mapping', 'interview_date'], name='interview_map_date_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='candidatejobmapping',
            index=models.Index(fields=['job', 'mapping_status'], name='map_job_status_idx'),
        ),
        migrations.AddIndex(
            model_name='candidatejobmapping',
            index=models.Index(fields=['recruiter_name'], name='map_recruiter_idx'),
        ),
        migrations.AddConstraint(
            model_name='candidatejobmapping',
            constraint=models.UniqueConstraint(fields=('candidate', 'job'), name='uniq_candidate_job'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_read', 'created_at'], name='notif_read_created_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['event_type'], name='notif_event_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['offer_status', 'offer_date'], name='offer_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='recruitmentstatus',
            index=models.Index(fields=['candidate', 'changed_at'], name='rstatus_cand_time_idx'),
        ),
        migrations.AddIndex(
            model_name='recruitmentstatus',
            index=models.Index(fields=['new_status'], name='rstatus_new_idx'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['parse_status', 'uploaded_at'], name='resume_status_upl_idx'),
        ),
    ]
