# Generated by Django 5.1.15 on 2026-07-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='current_ctc_fixed',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current fixed CTC in LPA (lakhs per annum).', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='current_ctc_variable',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current variable CTC in LPA (lakhs per annum).', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='expected_ctc_fixed',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Expected fixed CTC in LPA (lakhs per annum).', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='expected_ctc_variable',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Expected variable CTC in LPA (lakhs per annum).', max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='current_salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current CTC (legacy single figure).', max_digits=12, null=True),
        ),
    ]
