# Generated by Django 5.1.15 on 2026-07-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_candidate_current_ctc_fixed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='parse_flags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='job',
            name='closed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
